[tool.poetry]
name = "ml-ds"
version = "0.1.0"
description = ""
authors = ["Antonio Machado <antoniohenriquemachado08@gmail.com.br>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
